os:
  - linux

language: java

jdk:
  - openjdk8

sudo: true

env:
  - GRAALVM_VERSION="19.2.1"

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then DOWNLOAD_OS_NAME="darwin"; fi
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then DOWNLOAD_OS_NAME="linux"; fi
    echo $TRAVIS_OS_NAME
    curl -LJ "https://github.com/oracle/graal/releases/download/vm-$GRAALVM_VERSION/graalvm-ce-$DOWNLOAD_OS_NAME-amd64-$GRAALVM_VERSION.tar.gz" --output graalvm.tar.gz
    tar -xzf graalvm.tar.gz
    export GRAALVM_HOME=$(pwd)/graalvm-ce-$GRAALVM_VERSION
    export PATH=${GRAALVM_HOME}/bin:$PATH
    export JAVA_HOME=${GRAALVM_HOME}
    ${GRAALVM_HOME}/bin/gu install native-image
    sudo apt-get install build-essential libz-dev zlib1g-dev
script:
  - mvn package
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -f src/main/docker/Dockerfile.native -t shubhamtricon/quarkus-jvm:${TRAVIS_BUILD_ID} .
  - docker tag shubhamtricon/quarkus-jvm:${TRAVIS_BUILD_ID} shubhamtricon/quarkus-jvm:${TRAVIS_BUILD_ID}
  - docker push shubhamtricon/quarkus-jvm:${TRAVIS_BUILD_ID}