os:
  - linux

language: java

jdk:
  - openjdk8

sudo: true

env:
  - GRAALVM_VERSION="19.2.1"

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then DOWNLOAD_OS_NAME="darwin"; fi
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then DOWNLOAD_OS_NAME="linux"; fi
    echo $TRAVIS_OS_NAME
    curl -LJ "https://github.com/oracle/graal/releases/download/vm-$GRAALVM_VERSION/graalvm-ce-$DOWNLOAD_OS_NAME-amd64-$GRAALVM_VERSION.tar.gz" --output graalvm.tar.gz
    tar -xzf graalvm.tar.gz
    export GRAALVM_HOME=$HOME/Development/graalvm
    export PATH=${GRAALVM_HOME}/bin:$PATH
    export JAVA_HOME=${GRAALVM_HOME}
    ${GRAALVM_HOME}/bin/gu install native-image
    sudo apt-get install build-essential libz-dev zlib1g-dev
script:
  - native-image -jar target/code-with-quarkus-1.0.0-SNAPSHOT-runner.jar